                   SET COLOR TO W/B
                   @ 17,02 SAY " TRANSPORTADOR "
                                        @ 18,02 SAY "NOME.:"
                                        @ 18,09 SAY lTRANSNOM 
                                        @ 18,45 SAY "FRETE P/CONTA.:"
                                        @ 18,61 SAY lFRETE
                                        @ 19,02 SAY "PLACA:"
                                        @ 19,09 SAY lTRANSPL 
                                        @ 19,19 SAY "UF.:"
                                        @ 19,24 SAY lTRANPUF 
                                         @ 19,27 SAY "CGC/CPF.:"
                                         @ 19,36 SAY lTCGCPF 
                                         @ 19,57 SAY "I.E.:"
                                         @ 19,63 SAY lTRANIE 
                                         @ 20,02 SAY "ENDERECO.:"
                                         @ 20,13 SAY lTRANSEND 
                                         @ 20,40 SAY "MUNICIPIO:"
                                         @ 20,51 SAY lTRANSCID 
                                         @ 20,68 SAY "UF....:"
                                         @ 20,76 SAY lTRANSUF 
                                         @ 21,02 SAY "QTDE.:"
                                         @ 21,08 SAY lTRANSQTD 
                                         @ 21,16 SAY "ESPECIE.:"
                                         @ 21,26 SAY lTRANSESP 
                                         @ 21,29 SAY "MARCA..:"
                                         @ 21,38 SAY lTMARCA 
                                         @ 21,55 SAY "NUMERO.........:"
                                         @ 21,72 SAY lTRASNUM 
                                         @ 22,02 SAY "PESO BRUTO...:"
                                         @ 22,17 SAY lTRPBRT 
                                         @ 22,25 SAY "PESO LIQUIDO.................................:"
                                         @ 22,72 SAY lTRPLQ 
