* NTIVAR.PRG - VARIAVEIS DE INCLUSAO DE NOTAS
* AUTOR: ALEXSANDER SALINAS SANTOS - salinas@starmedia.com
* DATA: 27/10/1999


**************** PROCURANDO POR VARIAVEIS
        lEMISSAO = EMISSAO
        lSAIDA   = SAIDA
        lVENC    = VENC
        
        lOSAIDA   = OSAIDA
        lOPERACAO = OPERACAO
        lCFOP     = CFOP
        lNCLIEN   = NCLIEN
        lNTOTAL   = NTOTAL
        lTOTAL    = TOTAL
        lTOTAL1   = TOTAL1
        lTOTAL2   = TOTAL2
        lTOTAL3   = TOTAL3
        lTOTAL4   = TOTAL4
        lTOTAL5   = TOTAL5
        lSTOTAL   = STOTAL5
        lSTOTAL1  = STOTAL1
        lSTOTAL2  = STOTAL2
        lSTOTAL3  = STOTAL3
        lSTOTAL4  = STOTAL4
        lSTOTAL5  = STOTAL5
        
        lDESC1    = DESC1
        lUN1      = UN1
        lQTDA1    = QTDA1
        lUNIT1    = UNIT1
        lDESC2    = DESC2
        lUN2      = UN2
        lQTDA2    = QTDA2
        lUNIT2    = UNIT2
        lDESC3    = DESC3
        lUN3      = UN3
        lQTDA3    = QTDA3
        lUNIT3    = UNIT3

        lDESC4    = DESC4
        lUN4      = UN4
        lQTDA4    = QTDA4
        lUNIT4    = UNIT4
        
        lDESC5    = DESC5
        lUN5      = UN5
        lQTDA5    = QTDA5
        lUNIT5    = UNIT5
        
        lTICMS    = TICMS
        
        lSERV1    = SERV1
        lSUN1     = SUN1
        lSQTDA1   = SQTDA1
        lSUNIT1   = SUNIT1

        lSERV2    = SERV2
        lSUN2     = SUN2
        lSQTDA2   = SQTDA2
        lSUNIT2   = SUNIT2
        
        lSERV3    = SERV3
        lSUN3     = SUN3
        lSQTDA3   = SQTDA3
        lSUNIT3   = SUNIT3

        lSERV4    = SERV4
        lSUN4     = SUN4
        lSQTDA4   = SQTDA4
        lSUNIT4   = SUNIT4
        
        lSERV5    = SERV5
        lSUN5     = SUN5
        lSQTDA5   = SQTDA5
        lSUNIT5   = SUNIT5
        
        lNTOBS    = NTOBS
        lNTOBS2   = NTOBS2
        lOBSERV   = OBSERV
        lOBSERV2  = OBSERV2

        lICMS1    = ICMS1
        lVALICMS1 = VALICMS1
        lICMS2    = ICMS2
        lVALICMS2 = VALICMS2
        lICMS3    = ICMS3
        lVALICMS3 = VALICMS3
        lICMS4    = ICMS4
        lVALICMS4 = VALICMS4
        lICMS5    = ICMS5 
        lVALICMS5 = VALICMS5
        
        lDIAS     = DIAS
        lICMS     = ICMS
        lCICMS    = CICMS
        lISS      = ISS
        lVALORICMS = VALORICMS
        lTRANSNOM  = TRANSNOM
        lTRANSPL   = TRANSPL
        lTRANSUF   = TRANSUF
        lTCGCPF    = TCGCPF
        lTRANIE    = TRANIE 
        lTRANSEND  = TRANSEND
        lTRANPUF   = TRANSUF
        lTRANSCID  = TRANSCID
        lTRANSQTD  = TRANSQTD
        lTRANSESP  = TRANSESP
        lTMARCA    = TMARCA
        lTRASNUM   = TRASNUM 
        lTRPBRT    = TRPBRT
        lTRPLQ     = TRPLQ
        lFRETE     = FRENTE
        
        lvariavelDIF=" "
   ACAO=" "
   ACAO2=" "
   ACAO3=" "
   OPCAO0="  "
   REG=0
   pesquisaERRO=0

*******FINAL
