* NTIVAR.PRG - VARIAVEIS DE INCLUSAO DE NOTAS
* AUTOR: ALEXSANDER SALINAS SANTOS - salinas@starmedia.com
* DATA: 27/10/1999


**************** INICIO DAS VARIAVEIS
                
                ETDATA   = DATE()
                SDDATA   = DATE()
                lNTNUM   = 0
                *lEMISSAO = SPACE(8)
                *lSAIDA   = SPACE(8)
                *lVENC    = SPACE(8)

                lEMISSAO = ETDATA
                lSAIDA   = SDDATA
                lVENC    = lEMISSAO

                lOSAIDA   = SPACE(1)
                lOPERACAO = SPACE(27)
                lCFOP     = SPACE(4)
                lNCLIEN   = 0
                lNTOTAL   = 0
                lTOTAL    = 0
                lTOTAL1   = 0
                lTOTAL2   = 0
                lTOTAL3   = 0
                lTOTAL4   = 0
                lTOTAL5   = 0
                lSTOTAL   = 0
                lSTOTAL1  = 0
                lSTOTAL2  = 0
                lSTOTAL3  = 0
                lSTOTAL4  = 0
                lSTOTAL5  = 0

                lDESC1    = SPACE(42)
                lUN1      = SPACE(2)
                lQTDA1    = 0
                lUNIT1    = 0

                lDESC2    = SPACE(42)
                lUN2      = SPACE(2)
                lQTDA2    = 0
                lUNIT2    = 0

                lDESC3    = SPACE(42)
                lUN3      = SPACE(2)
                lQTDA3    = 0
                lUNIT3    = 0

                lDESC4    = SPACE(42)
                lUN4      = SPACE(2)
                lQTDA4    = 0
                lUNIT4    = 0
 
                lDESC5    = SPACE(42)
                lUN5      = SPACE(2)
                lQTDA5    = 0
                lUNIT5    = 0

                lTICMS    = 0
                lSERV1    = SPACE(55)
                lSUN1     = SPACE(2)
                lSQTDA1   = 0
                lSUNIT1   = 0

                lSERV2=SPACE(55)    
        lSUN2=SPACE(2)
        lSQTDA2=0
        lSUNIT2=0

        lSERV3=SPACE(55)
        lSUN3=SPACE(2)
        lSQTDA3=0
        lSUNIT3=0

        lSERV4=SPACE(55)
        lSUN4=SPACE(2)
        lSQTDA4=0
        lSUNIT4=0

        lSERV5=SPACE(55)
        lSUN5=SPACE(2)
        lSQTDA5=0
        lSUNIT5=0

 lNTOBS=SPACE(51)
 lNTOBS2=SPACE(55)
 lOBSERV=SPACE(51)
 lOBSERV2=SPACE(55)

        lICMS1=0
        lVALICMS1=0
        lICMS2=0
        lVALICMS2=0
        lICMS3=0
        lVALICMS3=0
        lICMS4=0
        lVALICMS4=0
        lICMS5    = 0
        lVALICMS5 = 0




 lDIAS=0
 lICMS=0
 lCICMS=0
 lISS=0
 lVALORICMS=0
 lTRANSNOM=SPACE(30)
 lTRANSPL=SPACE(7)
 lTRANSUF=SPACE(2)
 lTCGCPF=SPACE(18)
 lTRANIE=SPACE(15)
 lTRANSEND=SPACE(25)
 lTRANPUF=SPACE(2)
 lTRANSCID=SPACE(15) 
 lTRANSQTD=0
 lTRANSESP=SPACE(2)
 lTMARCA=SPACE(15)
 lTRASNUM=0
 lTRPBRT=SPACE(6)
 lTRPLQ=SPACE(6)
 lFRETE=SPACE(1)
 lvariavelDIF=" "
   ACAO=" "
   ACAO2=" "
   ACAO3=" "
   OPCAO0="  "
   REG=0
   pesquisaERRO=0

*******FINAL
